# Generated by Django 2.0.6 on 2018-06-16 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_per_day', models.SmallIntegerField()),
                ('follows_per_day', models.SmallIntegerField()),
                ('duration', models.DurationField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_login', models.CharField(blank=True, max_length=32)),
                ('inst_password', models.CharField(blank=True, max_length=64)),
                ('inst_profile_type', models.CharField(choices=[('n', 'New'), ('r', 'Recent'), ('e', 'Experienced')], default='e', max_length=1)),
                ('registered_at', models.DateField(auto_now_add=True)),
                ('plan_activation_datetime', models.DateTimeField()),
                ('account_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
