# Generated by Django 2.0.6 on 2018-06-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.CharField(default='Start', max_length=10),
            preserve_default=False,
        ),
    ]
