# Generated by Django 2.0.6 on 2018-06-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180618_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='plan_activation_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
