# Generated by Django 2.0.6 on 2018-12-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180618_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='inst_login',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='inst_password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='inst_profile_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='plan_activation_datetime',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='registered_at',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
