# Generated by Django 2.0.6 on 2018-12-17 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181217_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('count_game', models.IntegerField(default=0)),
                ('win_count_game', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('goal_1', models.IntegerField(default=0)),
                ('goal_2', models.IntegerField(default=0)),
                ('club_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_club', to='accounts.Club')),
                ('club_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_club', to='accounts.Club')),
            ],
        ),
        migrations.CreateModel(
            name='MatchBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Action')),
                ('id_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Club')),
                ('id_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Match')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='Tom', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='money_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='second_name',
            field=models.CharField(default='Jerry', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserGroup'),
            preserve_default=False,
        ),
    ]
