# Generated by Django 2.0.6 on 2018-12-17 18:15

from django.db import migrations

def combine_names(apps, schema_editor):
    Club = apps.get_model('accounts', 'Club')
    Club.objects.create(
        name='Juventus',
        count_game = 0,
        win_count_game = 0
    )
    Club.objects.create(
        name='Atletico',
        count_game = 0,
        win_count_game = 0
    )
    Club.objects.create(
        name='PSG',
        count_game = 0,
        win_count_game = 0
    )
    Club.objects.create(
        name='Manchecter United',
        count_game = 0,
        win_count_game = 0
    )
    Club.objects.create(
        name='Bayern',
        count_game = 0,
        win_count_game = 0
    )

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20181217_1808'),
    ]

    operations = [
        migrations.RunPython(combine_names)
    ]
