# Generated by Django 2.0.6 on 2018-12-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20181217_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
