# Generated by Django 2.1.4 on 2018-12-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20181218_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='match',
            name='description',
            field=models.CharField(default='desc', max_length=500),
            preserve_default=False,
        ),
    ]
