# Generated by Django 2.0.6 on 2018-12-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20181220_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='PPDA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='xPTS',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='xg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='xgA',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
