# Generated by Django 2.1.7 on 2019-03-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_matchaction_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
