# Generated by Django 2.1.7 on 2019-04-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_mertics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mertics',
            new_name='Mertic',
        ),
    ]
