# Generated by Django 2.1.7 on 2019-04-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20190404_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='count_game',
        ),
        migrations.RemoveField(
            model_name='club',
            name='win_count_game',
        ),
        migrations.RemoveField(
            model_name='match',
            name='PPDA',
        ),
        migrations.RemoveField(
            model_name='match',
            name='goal_1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='goal_2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='xPTS',
        ),
        migrations.RemoveField(
            model_name='match',
            name='xg',
        ),
        migrations.RemoveField(
            model_name='match',
            name='xgA',
        ),
    ]
