# Generated by Django 2.1.7 on 2019-04-22 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20190422_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='accounts.Match')),
                ('mertic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Mertic')),
            ],
        ),
    ]
